name: Build IPA
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Xcode
        run: sudo xcode-select -s /Applications/Xcode.app

      - name: Build App
        run: |
          xcodebuild -project App/App.xcodeproj -scheme App -configuration Release -sdk iphoneos CODE_SIGNING_ALLOWED=NO SUBMISSION_METHOD=local archive -archivePath $PWD/build/App.xcarchive
          mkdir -p $PWD/build/Payload
          cp -r $PWD/build/App.xcarchive/Products/Applications/*.app $PWD/build/Payload/
          cd $PWD/build
          zip -r App.ipa Payload

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: App-Package
          path: build/App.ipa
